language: python
python:
  - 3.6

env:
  global:
    # Doctr deploy key for pcdshub/pcdshub.github.io
    - secure: "DogN96dtirhfVvfoWmzIRG5wDna6K9TCfu5M/Dtq22NCQL+W/TMvUZS9XZGycQ1+vqsR7e3RZaMqwLKFL19c2FiSRf9g2drUb7UFAMd6lTgV4zKI/8ONe0AQQdWXLXsyfAv6KRvob7Y4Lhp1VZF8Q36J+KYGmxMreVgWIYdmjh0EP6HP+wM2ZbCYWv41ECv6DY71AUN8uDZUqRdiAg1ddbpEeKIKVqZ6Flqm71KXwMXpzUnG64FkMlrY2ne5nK27u1Xnn5yNN38Yg2A6giKnSWq9b0ZL8ouPAw8nF2BJlW2wUh6Hn38H/ZhOgbP/adZFG/yMmAe1qnbJ4ytzjxwh5y8A3u45ALTsuZGICHldtg6JZTEO4Etas0DE3wC4/Sup12kFF1a3Ex7AJWCtWK2yMnnMJi0djPD6fY0vBIOvelSn5Sy5dxKb16dwe5mPNLKX/YIXe2D6wvGf5RG6armb37f1cETj1K3porQ4j5hin605PKwk6HubJnLQeahAEX+m5nS3RtsBto1z6nO6gWKpxVhg9yk3uL8+eYY32cavB0jcv5Y4YctrWuh3RKnV3o8WLPM1JbKggvTJh0ytzqrDO3rnRL2ga13QxO/TcuYU0hGxnJGlkwTqDqKuJvsQgZH2+CCa59/TMGCmPFqjWoch1+1n8aLKcsrCXt4SfbfFeX4="

install:
  - pip install -r requirements.txt

script:
  - set -e
  - pip install doctr
  - make html
  - |
    if [[ "${TRAVIS_BRANCH}" == "source" ]]; then
      #Publish docs.
      echo "Deploying docs"
      doctr deploy . --no-require-master --built-docs build/html --deploy-branch-name master
    fi
